const  Asena  =  zorunlu ( '../events' ) ;
const  { MessageType }  =  zorunlu ( '@adiwajshing/baileys' ) ;

Asena . addCommand ( { model : 'sor' ,  fromMe : true } ,  ( zaman uyumsuz  ( mesaj ,  eşleşme )  =>  {

     mesaj bekliyoruz . sendMessage ( '*N*' ) ;
     mesaj bekliyoruz . sendMessage ( '*NE*' ) ;
     mesaj bekliyoruz . sendMessage ( '*NEP*' ) ;
     mesaj bekliyoruz . sendMessage ( '*NEPA*' ) ;
     mesaj bekliyoruz . sendMessage ( '*NEPARİZ*' ) ;

bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( '*S*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Se*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Sen*' ) ;
     mesaj bekliyoruz . sendMessage ( '😍 *Seni* 😍' ) ;

    bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( '*Ç*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Ço*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Çoo*' ) ;
     mesaj bekliyoruz . sendMessage ( '🥰 *Çook* 🥰' ) ;
    
    bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( '*S*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Se*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Sev*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Sevi*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviy*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviyo*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviyor*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviyoru*' ) ;
     mesaj bekliyoruz . sendMessage ( '💞 *Seviyorum* 💗' ) ;
    
    bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( 'Seni ♥️ Seviyorum' ) ;

} ) ) ;

Asena . addCommand ( { model : 'infoask' ,  fromMe : true } ,  ( zaman uyumsuz  ( mesaj ,  eşleşme )  =>  {

     mesaj bekliyoruz . sendMessage ( "*Codded by @Unique_hunter*\n*Seni seviyorum demenin güzel bir hali.*\n💻Kullanım: *.ask*" )

} ) ) ;
   
Asena . addCommand ( { model : 'aşk' ,  fromMe : true } ,  ( zaman uyumsuz  ( mesaj ,  eşleşme )  =>  {

     mesaj bekliyoruz . sendMessage ( '*I*' ) ;
     mesaj bekliyoruz . sendMessage ( '*IL*' ) ;
     mesaj bekliyoruz . sendMessage ( '*I Lo*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviyorum*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Seviyorum*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Y'yi Seviyorum*' ) ;
     mesaj bekliyoruz . sendMessage ( '* Yo'yu Seviyorum*' ) ;
     mesaj bekliyoruz . sendMessage ( '😍 *Seni Seviyorum* 😍' ) ;

    bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( '*S*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Yani*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Yani M*' ) ;
     mesaj bekliyoruz . sendMessage ( '*So Mu*' ) ;
     mesaj bekliyoruz . sendMessage ( '*Çok Muc*' ) ;
     mesaj bekliyoruz . sendMessage ( '💕 *Çok Fazla* 💞' ) ;

    bekliyoruz  yeni  söz ( r  =>  setTimeout ( R ,  1000 ) ) ;

     mesaj bekliyoruz . sendMessage ( 'Ben ♥️ Siz' ) ;

} ) ) ;

Asena . addCommand ( { model : 'infolove' ,  fromMe : true } ,  ( zaman uyumsuz  ( mesaj ,  eşleşme )  =>  {

     mesaj bekliyoruz . sendMessage ( "*Codded by @Unique_hunter*\n*Seni en iyi şekilde sevdiğimi söylemek için.*\n💻Kullanım: *.love*" )

} ) ) ;
